services:
  db:
    image: postgres:17.2
    container_name: finance-db
    ports: 
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: finance-backend
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/backend # not in production
  frontend:
    build: ./frontend
    container_name: finance-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend # not in production

volumes:
  db-data: