# Generated by Django 5.1.3 on 2025-01-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='name',
            field=models.CharField(default='Unknown Value', help_text="Full name as it appears on the receipt (e.g., 'Opos Uber *Eats Pending Uber.com').", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spending',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
